### ISSUE TITLE
Suggestion - Validate Date of Birth field to contain values only in the specified format

### ISSUE THREAD

**Issue by balasubramanian-dt** [dptstech/dpts-aushadam#11]
Validate “Date of Birth” field to be present only in the given format “DDDD-MM-YY” restricting all the characters to the allowed length only.

 Ex : A hypen can be added when the character length is specified”

2000-12-25

**Comment by Lavanya-nk** [comment]
Changes have been made. Please review and let me know in case of any issues.

**Comment by balasubramanian-dt** [comment]
Please validate the field to contain value only till the current Year, month and date

Refer to the attachment, it shows that a record is updated with a year 2021 which has not come yet

![Screenshot from 2020-10-06 13-12-38](https://user-images.githubusercontent.com/71746146/95173112-e0731900-07d5-11eb-93c4-4179d96f98fd.png)
![Screenshot from 2020-10-06 13-09-54](https://user-images.githubusercontent.com/71746146/95173115-e1a44600-07d5-11eb-9b7c-8fbba49cc7ee.png)

**Comment by Lavanya-nk** [comment]
Issue fixed and code is checked in. Please validate and let me know in case of any issues.
