### ISSUE TITLE
Suggestion - Records can be sorted in the Search Patients window, preferably by Name 

### ISSUE THREAD

**Issue by balasubramanian-dt** [dptstech/dpts-aushadam#12]
Records can be sorted in the Search Patients window, preferably by Name

**Comment by Lavanya-nk** [comment]
Changes have been made. Please review and let me know in case of any issues.

**Comment by balasubramanian-dt** [comment]
Enhancement request completed and verified
Sorting in search window is now populated by Patient Name

**Suggestion would be that it will look more uniform if the records are left aligned to the column header**
