### ISSUE TITLE
Bug - Selecting a initially created Patient record from search patient window does not fetch the email details

### ISSUE THREAD

**Issue by balasubramanian-dt** [dptstech/dpts-aushadam#14]
Bug - Selecting a initially created Patient record from search patient window does not fetch the email details

Refer to the attachment for details
![Screenshot from 2020-09-25 15-06-21](https://user-images.githubusercontent.com/71746146/94251848-c36e5880-ff40-11ea-9b0c-0334efb45d49.png)
![Screenshot from 2020-09-25 14-38-55](https://user-images.githubusercontent.com/71746146/94251854-c49f8580-ff40-11ea-97b1-524daf5b6b4c.png)

**Comment by Lavanya-nk** [comment]
Issue fixed and code is checked in. Please validate and let me know in case of any issues.

**Comment by balasubramanian-dt** [comment]
Verified and works as expected, the email address field value is now fetched as expected and also able to update
Bug can be moved to status Fixed and Closed
