### ISSUE TITLE
Bug - Alternate Mobile Number not fetched when selecting the Patient from the search window

### ISSUE THREAD

**Issue by balasubramanian-dt** [dptstech/dpts-aushadam#18]
Alternate Mobile Number not fetched when selecting the Patient from the search window

**Comment by Lavanya-nk** [comment]
Issue fixed and code is checked in. Please validate and let me know in case of any issues.

**Comment by balasubramanian-dt** [comment]
Mobile number and Alternate mobile number details fetched as expected.
This issue is fixed and can be closed, but it does not allow to update the Mobile and Alternate mobile number field, for this issue a seperate bug has been created " Bug # 20"

**Comment by balasubramanian-dt** [comment]
Issue not fixed correctly, creates another issue when fetching the record from search window after updating the alternate mobile number field

Steps to reproduce
1. Select a patient from Search window where no Alternate mobile number field is given
2. Provide a number and click Save
3. Record will be saved successfully
4. Clear the window
5. Select another patient from search window
6. Expected result : The details of the selected patient record only should be fetched and shown
7. ACTUAL RESULT : The Alternate mobile number field shows the last saved value of the previous selected patient

I updated the alternate mobile number to"12345" only for the Patient Record ID "20200925-142858" ,it was updated successfully, but when i cleared the window and selected another patient from the search window, it showed the Alternate mobile number given for the patient record id "20200925-142858" , and this occurs for all the patients which is selected 

Refer to the attachments for the screen shots of the issue
![Screenshot from 2020-10-06 14-37-45](https://user-images.githubusercontent.com/71746146/95182571-70b75b00-07e2-11eb-86cb-5ed6b26376ae.png)

![Screenshot from 2020-10-06 14-37-32](https://user-images.githubusercontent.com/71746146/95182576-714ff180-07e2-11eb-84b2-844c1a67ed0e.png)

![Screenshot from 2020-10-06 14-37-21](https://user-images.githubusercontent.com/71746146/95182579-71e88800-07e2-11eb-8923-c705afa6867c.png)

![Screenshot from 2020-10-06 14-39-48](https://user-images.githubusercontent.com/71746146/95182560-6eed9780-07e2-11eb-85ac-69a491d46c25.png)
![Screenshot from 2020-10-06 14-38-29](https://user-images.githubusercontent.com/71746146/95182562-6f862e00-07e2-11eb-9389-eb01460dd03a.png)
![Screenshot from 2020-10-06 14-38-16](https://user-images.githubusercontent.com/71746146/95182567-701ec480-07e2-11eb-8390-31dbfbfed281.png)


Screen shots of other selected patients which shows the Alternate mobile number which is last saved
![Screenshot from 2020-10-06 14-47-02](https://user-images.githubusercontent.com/71746146/95183471-a6107880-07e3-11eb-9c7a-c2d54cd5d419.png)
![Screenshot from 2020-10-06 14-46-45](https://user-images.githubusercontent.com/71746146/95183475-a7da3c00-07e3-11eb-8f3d-937db437b58b.png)
![Screenshot from 2020-10-06 14-46-23](https://user-images.githubusercontent.com/71746146/95183477-a872d280-07e3-11eb-8e91-ce6c8926efcc.png)
![Screenshot from 2020-10-06 14-45-59](https://user-images.githubusercontent.com/71746146/95183478-a90b6900-07e3-11eb-8354-4de2e8c232dd.png)
![Screenshot from 2020-10-06 14-45-44](https://user-images.githubusercontent.com/71746146/95183479-a9a3ff80-07e3-11eb-81bc-969ff902d09b.png)
![Screenshot from 2020-10-06 14-39-48](https://user-images.githubusercontent.com/71746146/95183482-aa3c9600-07e3-11eb-90b1-8210a1cce346.png)

**Comment by Lavanya-nk** [comment]
Code fix is checked in. Please validate and let me know in case of any issues.

**Comment by balasubramanian-dt** [comment]
Mobile number and Alternate mobile number is fetched properly and verified, issue is solved
