### ISSUE TITLE
Bug - Save button icon image not appearing after saving the initial test report 

### ISSUE THREAD

**Issue by balasubramanian-dt** [dptstech/dpts-aushadam#24]
Save button icon image not appearing after saving the initial test report 

Before Saving the record
![Screenshot from 2020-10-06 21-48-15](https://user-images.githubusercontent.com/71746146/95230529-a75f9680-081f-11eb-8a11-24e943afd3d4.png)

After Saving the record
![Screenshot from 2020-10-06 21-48-27](https://user-images.githubusercontent.com/71746146/95230523-a62e6980-081f-11eb-927a-cc6459e7b63f.png)

**Comment by Lavanya-nk** [comment]
Issue fixed and code is checked in. Please validate and let me know in case of any issues.

**Comment by balasubramanian-dt** [comment]
Verified and confirm the issue is solved
