### ISSUE TITLE
Bug - Incorrect Prompt during update of a patient detail

### ISSUE THREAD

**Issue by balasubramanian-dt** [dptstech/dpts-aushadam#3]
Incorrect Prompt during update of a patient detail, Prompts that Gender is Mandatory even though it is selected, Happens when the Date of Birth field is updated and Save is clicked[
![Screenshot from 2020-09-25 08-49-09](https://user-images.githubusercontent.com/71746146/94226153-7a081400-ff14-11ea-9059-307be7c8deed.png)
![Screenshot from 2020-09-25 08-58-22](https://user-images.githubusercontent.com/71746146/94226156-7bd1d780-ff14-11ea-96d4-fe3a433f748b.png)

](url)

**Comment by Lavanya-nk** [comment]
Issue fixed and code is checked in. Please validate and let me know in case of any issues.

**Comment by balasubramanian-dt** [comment]
Bug Re-opened as it allows to save a new record without selecting the Gender
**Steps to Reproduce
1. Specify Patient Name
2. Specify the Mobile and Alternate number
3. Specify email address
4. Specify Date of birth in the given format
****NOTE***
5. Edit the Date of Birth with an invalid format such as ex: 2000-22-31 or 1999/12/31 or 2021-01-01 and click Save
6. The application will prompt for a valid format for Date of Birth
7. Specify a valid data ex: 1999-12-31, DO NOT SELECT THE "GENDER" which is a mandatory field and click Save
8."Patient Record Created" message is displayed, which should not be done, when the mandatory field "Gender" is not selected, and it should have prompted to "Select Gender"

Attachment
![Screenshot from 2020-10-06 11-48-56](https://user-images.githubusercontent.com/71746146/95166162-fc24f200-07ca-11eb-89b8-c3557717a208.png)

**Comment by Lavanya-nk** [comment]
Issue fixed and code is checked in. Please validate and let me know in case of any issues.

**Comment by balasubramanian-dt** [comment]
Verified that the issue is fixed and be resolved and marked as Closed
