### ISSUE TITLE
Bug - Application terminates abruptly, need to confirm the scenario, it happened when a invalid date of birth format is specified and the search or save button is clicked

### ISSUE THREAD

**Issue by balasubramanian-dt** [dptstech/dpts-aushadam#4]
Application terminates abruptly, need to confirm the scenario, it happened when a invalid date of birth format is specified and the search or save button is clicked
       
       Error shown in Terminal
       ==================
       save inside patinet controller: {'patient_id': '20200925-091010', 'patient_name': 'TEST', 'mobile_no': '!@%$^@%&%^&%^#&', 'dob': '19800-02-12', 'gender': 'Male', 'alternate_mob': 'wrrw5', 'email_id': 'fsfsd'}
        1. [INFO   ] [Base        ] Leaving application in progress...
        2.  Traceback (most recent call last):
        3.    File "aushadam.py", line 120, in <module>
        4.      ClinicManagementSystem().run()
        5.    File "/usr/lib/python3/dist-packages/kivy/app.py", line 826, in run
        6.      runTouchApp()
        7.    File "/usr/lib/python3/dist-packages/kivy/base.py", line 502, in runTouchApp
        8.      EventLoop.window.mainloop()
        9.    File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
        10.      self._mainloop()
        11.    File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
        12.      EventLoop.idle()
        13.    File "/usr/lib/python3/dist-packages/kivy/base.py", line 337, in idle
        14.      Clock.tick()
        15.    File "/usr/lib/python3/dist-packages/kivy/clock.py", line 581, in tick
        16.      self._process_events()
        17.    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
        18.    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
        19.    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
        20.    File "kivy/_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
        21.    File "kivy/_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
        22.    File "/usr/lib/python3/dist-packages/kivy/weakmethod.py", line 56, in is_dead
        23.      return self.proxy is not None and not bool(dir(self.proxy))
        24.  ReferenceError: weakly-referenced object no longer exists
        25. Error in sys.excepthook:

**Comment by Lavanya-nk** [comment]
Unable to replicate the issue. Save and search works fine when invalid date is added(a message is displayed)

**Comment by balasubramanian-dt** [comment]
Issue can be closed as it prompts for a valid date format when searching or saving with an invalid date format or data
